### PR TITLE
VDR added

### PR DESCRIPTION
**Pull request by joabakk**

### CODE REVIEW

**Comment by joabakk** [comment]
Don't know why it continues to fail

**Comment by jmwooten** [comment]
The VDR sentence type has the following six fields:
$--VDR,x.x,T,x.x,M,x.x,N*hh
1) Degress True
2) T = True
3) Degrees Magnetic
4) M = Magnetic
5) Knots (speed of current) 
6) N = Knots

What you supplied only contains 4 fields.

**Comment by joabakk** [comment]
Had a paranthesis too much open...

**Comment by Knio** [comment]
I fixed up some of the field names, I think you missed Km/Knots, and I made them consistent with the VPW fields (unit_*)

**Pull request merged**
