### PR TITLE
Added the additional [optional] types to the RMC message including:

### PR DESCRIPTION
**Pull request by barbacbd**
- Mode Indicator
- Navigation Status

The tests were added as a single test case with many subcases.

Fix for #118

### CODE REVIEW

**Comment by barbacbd** [comment]
@Knio Any way to add you as a reviewer?

**Comment by Knio** [comment]
Can you fix the failing tests?

**Comment by barbacbd** [comment]
@Knio Looks like it is good to go. Apparently I forgot to format the super() call for python2.7

**Comment by wodny** [comment]
@Knio
I think that the new `is_valid` implementation should contain a warning in a docstring as it causes a regression for multiple device models (eg. modems with GPS) when upgrading from 1.18 to 1.19. It seems that some of the devices always return `V` for the navigational status as they do not implement it but still return messages in the extended NMEA 4.10 format. For those devices `status == "A"` seems better.

**Pull request merged**
