### PR TITLE
nmea_utils: Added timezone

### PR DESCRIPTION
**Pull request by barbacbd**
** UTC timezone is applied when returning the information from datetime.

Fix applied for #100

### CODE REVIEW

**Comment by barbacbd** [comment]
@Knio Looks like another python incompatibility. I fixed that, so can you give this a once over (or twice) for me?

**Comment by Knio** [comment]
is there a way to only require the install dep on py2.7, and use `datetime.timezone.utc` on py3? I don't want to introduce unnecessary 3rd party dependencies

**Comment by barbacbd** [comment]
Sure I can do some import "magic" If you want. Some people want to use the same deps for everything and some want what you want. You never know until you try right! I will make that change .

**Comment by barbacbd** [comment]
Actually it looks like it was python 2.7, and < 3.6

**Comment by barbacbd** [comment]
@Knio hopefully I have what you wanted pushed here. May need to rerun the tests as I pushed something prematurely earlier. The tests pass in 2.7, 3.6, and 3.8 on my system .

**Comment by barbacbd** [comment]
@Knio is this one good to go or do you need more changes ?

**Comment by barbacbd** [comment]
@Knio can we close this one or merge or other haha? I have it still sitting in my queue

**Comment by barbacbd** [comment]
@Knio this has conflicts with the main branch. Looks like you may have added something similar. Is this safe to close ?

**Comment by Knio** [comment]
Hey, yes I did. Are you able to confirm if what's in `master` solves the problem for you?

**Comment by barbacbd** [comment]
Should work for me.

**Pull request closed without merging**
