### PR TITLE
Add support for Nortek Doppler Velocity Logs (DVLs)

### PR DESCRIPTION
**Pull request by kledom**
Add suppport for Nortek Doppler Velocity Logs (DVLs). Message definitions are based on Nortek's DVL-IntegratorsGuide.

### CODE REVIEW

**Comment by Knio** [comment]
Thanks!

**Comment by Knio** [comment]
Oops, the unit tests were failing here. so I reverted. Looks like Travis-CI has broken something and so it didn't trigger properly on the PR. Can you fix the tests and confirm and hopefully I will fix CI?

**Comment by kledom** [comment]
Can you provide any error message?
Pytest is running successfully on my machine (see attachment)
[results.txt](https://github.com/Knio/pynmea2/files/6292655/results.txt)

**Comment by Knio** [comment]
Here's the travis result: https://travis-ci.org/github/Knio/pynmea2/builds/766696154

**Comment by Knio** [comment]
CI should be fixed now, so if you make make another PR the checks should show up inline. See #126

**Comment by kledom** [comment]
Hm I guess the reason for the different results are timezone settings. Since the `datetime` parameter tzinfo=timezone.utc requires Python3.2 things get a little complicated. 
Any suggestions? Change the tests so that they pass on UTC systems?

**Comment by kledom** [comment]
NVM. #127 That'll do.

**Pull request merged**
