### PR TITLE
Added NMEAFile class

### PR DESCRIPTION
**Pull request by lobocv**
I've added a NMEAFile class that behaves just like a python file object. This class can be used to read NMEASentence objects from files in a manner analogous to the python file object. This means you can iterate through the NMEAFile object, call read() to return a list of all the lines as NMEASentences.

For example:
`

    with pynmea.NMEAFile(filepath) as f:
        for nmea_string in f:
                print nmea_string.latitude, nmea_string.longitude

`

### CODE REVIEW

**Comment by lobocv** [comment]
I am new to this continuous-integration gig. I understand the concept but have never used it.
I also realized that this PR is not forward compatible with python 3 due to the subclassing of file. I'm not sure the best way to go about that. Perhaps hold off until I settle that.

**Comment by Knio** [comment]
Do you think you could upgrade/extend the NMEAStreamReader class for this? it does something very similar.

Usually as long as you implement the same interface (open, close, __iter__, __next__) as file you don't need to actually inherit from it, or maybe look at using an ABC from https://docs.python.org/3/library/io.html

**Comment by jmwooten** [comment]
NMEAStreamReader would definitely be a good place to start. I think the example use case is interesting.  I may be missing the subtlety but that's going to call f.next() over and over, which NMEAStreamReader already provides. 

NMEAStreamReader.next() by default calls readline, but would act like read if a buffer were passed. 

What else are you looking for by emulating "file" vs calling open and using the object through StreamReader?

**Comment by lobocv** [comment]
Well the problem I have (and hopefully you can clear it up) is 
1) That next() was returning lists of what seems like single NMEASentences.

2) Requirement of an infinite while loop around a call to next() in order to read the entire file. I did not like the example have having an infinite while loop around a call to next() in order to read a file because it never exits once the file is exhausted.

My inclination is that it was designed to read from a source of constantly updating information (a steam). In that case it is of course useful to continuously call next() in a while loop. It was because I did not fully understand the purpose of the NMEAStreamReader that I did not subclass it/extend it.

If in fact it is meant to read from a constantly updating source I feel it might be simpler to have the NMEAFile.

I've taken @Knio 's comments to heart and they worked out. By implementing the same interface through defining of __iter__(), __enter__(), __exit__(), open(), close() I've successfully ran the test scripts on python 2.7 and 3.4.

**Comment by lobocv** [comment]
On a different note, is there a way to update this PR with the new commits I have? Or do I have to create a new PR?

**Comment by jmwooten** [comment]
You can update it. Just by updating the pull request, I've done it before without issue.

You're right that next is returning a list of 1 NMEASentence if you call it on a buffer because it reads the next NMEASentence. It probably makes more sense for it to mimic the next, readline, and read you previously outlined in NMEAFile. Right now next() is trying to do too much. 

Your inclination is correct that it's designed to run on i/o streams. However, it is expected to work in your use case. It might need to be revised.

**Comment by lobocv** [comment]
I'm also having difficulties with the continuous integration script failing because the example nmea_file file I've added can't be found. Not sure what is going wrong here.

**Comment by jmwooten** [comment]
It's potentially because the continuous integration installs the library and then runs the test. IF the file is not part of the install then it won't be able to locate it. Can you mimic the file in the test_file.py?

**Comment by lobocv** [comment]
I looks like I have finally passed the test. This was a nice experience to learn some CI. I really like how you have it set up. I've got to look into implementing that on my projects.

I'll leave it up to you if you want to accept the NMEAFile feature.

**Comment by Knio** [comment]
I cleaned this up a little bit (made NMEAFile take an already existing file, and used StringIO to emulate a file in the test so it's not touching the filesystem). Merged and published 1.5.0

I would still really like to see NMEAFile and NMEAStreamReader combined (maybe just move the buffer interface from StreamReader into NMEAFile?), but I don't know enough about the use case of each class to be sure of what features are useful/required.

**Comment by lobocv** [comment]
I'm with you too, I would like to see them combined because I think they are fairly similar. I think it just clicked in my head why you wrote NMEAStreamReader.next() the way you did. The challenge is having the class understand when it reaches EOF, which is never in the case of a stream and finite for a file. Iterating over file objects is nice because you automatically kick out of the loop when reaching EOF.

Perhaps NMEAStreamReader's next() function can be renamed to something like poll(). I think this may be a more descriptive name and lets you keep the functionality. That way, we can still iterate through a file and get a EOF signal but we can also repeatedly call poll()in the case where we expect the file/stream to update as we read.

**Comment by jmwooten** [comment]
I concur with the .poll(). That's effectively what it's doing. It is after all expecting a file-like stream with no EOF.

**Pull request merged**
