### PR TITLE
add is_valid() helper method

### PR DESCRIPTION
**Pull request by ckuethe**
As discussed in https://github.com/Knio/pynmea2/pull/37 here's a diff to add a boolean status to the parser.

It returns True iff the sentence has a status field equal to 'A', and None if there is no status field. Thus, you can safely call is_valid() on any sentence and know whether the data is good, bad, or can't-say.

### CODE REVIEW

**Comment by Knio** [comment]
What do you think of making this into a mixin class like https://github.com/Knio/pynmea2/blob/master/pynmea2/nmea_utils.py#L41 ?

That way it can only be on the 3 classes that need it, and the status property is guaranteed to exist

**Comment by ckuethe** [comment]
I'm not sure I like it but I'll try it..

**Comment by ckuethe** [comment]
Note that GSA and GGA don't have specific 'status' fields; for the purpose of checking fix quality I want the receiver to say that it has at least a 2D fix, and various DGPS modes are OK.

**Comment by Knio** [comment]
Thanks! The other is_valid checks are cool.

I added some tests to the new properties and published the new version. If a mixin is only going to apply to a single class you could just add it to the class directly instead of make a mixin, but this seems fine to have them all in the same place.

**Pull request merged**
